"""Initial migration

Revision ID: 02e36ce00c43
Revises: 
Create Date: 2026-01-28 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02e36ce00c43"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_server", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("subscription_model", sa.String(), nullable=False),
        sa.Column("post_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "api_server",
            "domain",
            "user",
            "subscription_model",
            "post_url",
            name="_subscription_uc",
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_api_server"),
        "subscriptions",
        ["api_server"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_domain"), "subscriptions", ["domain"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user"), "subscriptions", ["user"], unique=False
    )

    op.create_table(
        "oauth_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_server", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_server", "domain", "user", name="_credential_uc"),
    )
    op.create_index(
        op.f("ix_oauth_credentials_api_server"),
        "oauth_credentials",
        ["api_server"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_credentials_domain"),
        "oauth_credentials",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_credentials_id"), "oauth_credentials", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_credentials_user"), "oauth_credentials", ["user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_credentials_user"), table_name="oauth_credentials")
    op.drop_index(op.f("ix_oauth_credentials_id"), table_name="oauth_credentials")
    op.drop_index(op.f("ix_oauth_credentials_domain"), table_name="oauth_credentials")
    op.drop_index(
        op.f("ix_oauth_credentials_api_server"), table_name="oauth_credentials"
    )
    op.drop_table("oauth_credentials")

    op.drop_index(op.f("ix_subscriptions_user"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_domain"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_api_server"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
